-- phpMyAdmin SQL Dump
-- version 4.3.9
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Mar 23, 2015 at 10:27 AM
-- Server version: 5.6.23
-- PHP Version: 5.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `concept-map-builder`
--

-- --------------------------------------------------------

--
-- Table structure for table `concept-maps`
--

CREATE TABLE IF NOT EXISTS `concept-maps` (
  `map_id` int(4) NOT NULL,
  `map_data` text NOT NULL,
  `map_created_by` varchar(25) NOT NULL,
  `created_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1248 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `concept-maps`
--

INSERT INTO `concept-maps` (`map_id`, `map_data`, `map_created_by`, `created_on`) VALUES
(1233, '{\r\n    "nodes": [\r\n        {\r\n            "name": "adnan",\r\n            "id": 10,\r\n            "x": 109,\r\n            "y": 142.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "adb"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "aa"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "adnan",\r\n            "id": 11,\r\n            "x": 398,\r\n            "y": 248.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "asasjsja"\r\n                },\r\n                {\r\n                    "name": "shshsh"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "sjsjsj11"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "adnan2",\r\n            "id": 12,\r\n            "x": 57,\r\n            "y": 342.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "sjsj3"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "hhss"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-22 17:40:23'),
(1234, '{\r\n    "nodes": [\r\n        {\r\n            "name": "1",\r\n            "id": 10,\r\n            "x": 196,\r\n            "y": 65.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "New Node",\r\n            "id": 12,\r\n            "x": 199,\r\n            "y": 538.0000267028809,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 5\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 1\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-22 19:02:15'),
(1235, '{\r\n    "nodes": [\r\n        {\r\n            "name": "1",\r\n            "id": 10,\r\n            "x": 196,\r\n            "y": 65.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "New Node",\r\n            "id": 12,\r\n            "x": 199,\r\n            "y": 538.0000267028809,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 5\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 1\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-22 19:03:09'),
(1236, '{\r\n    "nodes": [\r\n        {\r\n            "name": "1",\r\n            "id": 10,\r\n            "x": 196,\r\n            "y": 65.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "New Node",\r\n            "id": 12,\r\n            "x": 199,\r\n            "y": 538.0000267028809,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 5\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 1\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-22 19:03:29'),
(1237, '{\r\n    "nodes": [\r\n        {\r\n            "name": "1",\r\n            "id": 10,\r\n            "x": 196,\r\n            "y": 65.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "New Node",\r\n            "id": 12,\r\n            "x": 199,\r\n            "y": 538.0000267028809,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                },\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "New connector"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 5\r\n            },\r\n            "dest": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 1\r\n            }\r\n        },\r\n        {\r\n            "source": {\r\n                "nodeID": 12,\r\n                "connectorIndex": 0\r\n            },\r\n            "dest": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 2\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-22 19:07:32'),
(1238, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 02:51:41'),
(1239, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 02:53:54'),
(1240, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 02:57:54'),
(1241, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 02:58:21'),
(1242, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 03:13:08'),
(1243, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 03:17:58'),
(1244, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 03:42:19'),
(1245, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 04:20:35'),
(1246, '{\r\n    "nodes": [\r\n        {\r\n            "name": "Adnan",\r\n            "id": 10,\r\n            "x": 222,\r\n            "y": 169.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "1"\r\n                },\r\n                {\r\n                    "name": "2"\r\n                },\r\n                {\r\n                    "name": "4"\r\n                },\r\n                {\r\n                    "name": "3"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "2",\r\n            "id": 11,\r\n            "x": 497,\r\n            "y": 398.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "5"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "4"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 3\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 04:42:18'),
(1247, '{\r\n    "nodes": [\r\n        {\r\n            "name": "sncshdcs",\r\n            "id": 10,\r\n            "x": 137,\r\n            "y": 175.99999618530273,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "jxncjsnc"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "jsnjcnsdc"\r\n                },\r\n                {\r\n                    "name": "ncsncjnscn"\r\n                }\r\n            ],\r\n            "width": 250\r\n        },\r\n        {\r\n            "name": "jncjscn",\r\n            "id": 11,\r\n            "x": 454,\r\n            "y": 282.99999713897705,\r\n            "inputConnectors": [\r\n                {\r\n                    "name": "sdncsc"\r\n                }\r\n            ],\r\n            "outputConnectors": [\r\n                {\r\n                    "name": "jnscsjnc"\r\n                }\r\n            ],\r\n            "width": 250\r\n        }\r\n    ],\r\n    "connections": [\r\n        {\r\n            "source": {\r\n                "nodeID": 10,\r\n                "connectorIndex": 1\r\n            },\r\n            "dest": {\r\n                "nodeID": 11,\r\n                "connectorIndex": 0\r\n            }\r\n        }\r\n    ]\r\n}', 'Adnan Shafique', '2015-03-23 10:26:42');

-- --------------------------------------------------------

--
-- Table structure for table `input_connection`
--

CREATE TABLE IF NOT EXISTS `input_connection` (
  `node_id` int(4) NOT NULL,
  `connector_code` int(2) NOT NULL,
  `connector_name` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `nodes`
--

CREATE TABLE IF NOT EXISTS `nodes` (
  `map_id` int(4) NOT NULL,
  `node_id` int(4) NOT NULL,
  `nodeID` int(2) NOT NULL,
  `nodeName` varchar(60) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=1007 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `nodes`
--

INSERT INTO `nodes` (`map_id`, `node_id`, `nodeID`, `nodeName`) VALUES
(1233, 1001, 10, 'adnan'),
(1245, 1002, 11, '2'),
(1246, 1003, 10, 'Adnan'),
(1003, 1004, 11, '2'),
(1247, 1005, 10, 'sncshdcs'),
(1005, 1006, 11, 'jncjscn');

-- --------------------------------------------------------

--
-- Table structure for table `output_connection`
--

CREATE TABLE IF NOT EXISTS `output_connection` (
  `node_id` int(4) NOT NULL,
  `connector_code` int(2) NOT NULL,
  `connector_name` varchar(60) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `concept-maps`
--
ALTER TABLE `concept-maps`
  ADD PRIMARY KEY (`map_id`) COMMENT 'Primary key autoincrement';

--
-- Indexes for table `nodes`
--
ALTER TABLE `nodes`
  ADD PRIMARY KEY (`node_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `concept-maps`
--
ALTER TABLE `concept-maps`
  MODIFY `map_id` int(4) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1248;
--
-- AUTO_INCREMENT for table `nodes`
--
ALTER TABLE `nodes`
  MODIFY `node_id` int(4) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=1007;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
